# Generated by Django 4.2.7 on 2023-11-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map_app', '0002_remove_location_name_alter_location_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='loc', editable=False, max_length=250, unique=True),
        ),
    ]
