# Generated by Django 4.2.7 on 2023-11-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map_app', '0003_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(editable=False, max_length=250),
        ),
    ]
