# Generated by Django 4.2.7 on 2023-11-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map_app', '0011_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.IntegerField(default=11),
        ),
    ]
