# Generated by Django 4.2.7 on 2023-11-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map_app', '0012_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
