# Generated by Django 4.2.7 on 2023-11-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map_app', '0013_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
