# Generated by Django 4.2.7 on 2023-11-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map_app', '0015_remove_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='temperature_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
