# Generated by Django 4.2.7 on 2023-11-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map_app', '0016_location_temperature_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
